### ISSUE TITLE
Use of your tool

### ISSUE THREAD

**Issue by Cherrylexie-love** [jonmbake/person-activity-fit-diagnostic#2]
Hi Jon, 

I came across your cool tool and would like to use it but am wondering if there is any data privacy protection.  

I would like to be able to send to clients to fill out (I am a coach) but here is nothing on the site about the author or abiding by data protection so some clients may not want to fill it out.  No worries if not possible :-)  

Thanks

**Comment by jonmbake** [comment]
Hi @Cherrylexie-love.

I added a [privacy statement to the website](https://pathtohappier.com/privacy-policy.html) with a link at the bottom of the website. The privacy statement simply says:

> This website does not collect any visitor information.

Let me know if there is anything else.

Thanks,
Jon

**Comment by Cherrylexie-love** [comment]
Hi Jon, That is awesome - also might be good to link to your website so people know who you are.  I have shared to fellow students on a Positive Psychology masters degree so you might see some increased use.  Thanks again for the quick response!
